//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioRopa.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioRopa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 0dBm 的當地語系化字串。
        /// </summary>
        public static string _0dBm {
            get {
                return ResourceManager.GetString("0dBm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 20dBm 的當地語系化字串。
        /// </summary>
        public static string _20dBm {
            get {
                return ResourceManager.GetString("20dBm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AGC (Automatic Gein Control): 的當地語系化字串。
        /// </summary>
        public static string AGC {
            get {
                return ResourceManager.GetString("AGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AGC (Automatic Gein Control) 的當地語系化字串。
        /// </summary>
        public static string AGCTitle {
            get {
                return ResourceManager.GetString("AGCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APR-1 的當地語系化字串。
        /// </summary>
        public static string APRDeviceText {
            get {
                return ResourceManager.GetString("APRDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1. Please connect the APR-1 dedicated cable to the computer. 的當地語系化字串。
        /// </summary>
        public static string AprTransferSsentence1 {
            get {
                return ResourceManager.GetString("AprTransferSsentence1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2.  Click the &quot;Transfer&quot; button below. 的當地語系化字串。
        /// </summary>
        public static string AprTransferSsentence2 {
            get {
                return ResourceManager.GetString("AprTransferSsentence2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 3. When the APR-1’s purple indicator flashes rapidly three times, it means the transfer is successful and the cable can be disconnected. 的當地語系化字串。
        /// </summary>
        public static string AprTransferSsentence3 {
            get {
                return ResourceManager.GetString("AprTransferSsentence3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 4. To transfer to another APR-1, please repeat the steps above. 的當地語系化字串。
        /// </summary>
        public static string AprTransferSsentence4 {
            get {
                return ResourceManager.GetString("AprTransferSsentence4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APT-1 的當地語系化字串。
        /// </summary>
        public static string APTDeviceText {
            get {
                return ResourceManager.GetString("APTDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auracast Channel Name 的當地語系化字串。
        /// </summary>
        public static string AuracastChannelName {
            get {
                return ResourceManager.GetString("AuracastChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auracast Information 的當地語系化字串。
        /// </summary>
        public static string AuracastInformation {
            get {
                return ResourceManager.GetString("AuracastInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auracast Information Setting 的當地語系化字串。
        /// </summary>
        public static string AuracastInfoSetting {
            get {
                return ResourceManager.GetString("AuracastInfoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auracast Priority Setting 的當地語系化字串。
        /// </summary>
        public static string AuracastPriority {
            get {
                return ResourceManager.GetString("AuracastPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Channel Name: 的當地語系化字串。
        /// </summary>
        public static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose Your Device 的當地語系化字串。
        /// </summary>
        public static string ChooseYourDevice {
            get {
                return ResourceManager.GetString("ChooseYourDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connect 的當地語系化字串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connection: 的當地語系化字串。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connect to APR-1 的當地語系化字串。
        /// </summary>
        public static string ConnectToApr {
            get {
                return ResourceManager.GetString("ConnectToApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 dBm 的當地語系化字串。
        /// </summary>
        public static string dBm {
            get {
                return ResourceManager.GetString("dBm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device Name: 的當地語系化字串。
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disconnect 的當地語系化字串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APR-1 is not connected. 的當地語系化字串。
        /// </summary>
        public static string Error_Apr_Not_Connect {
            get {
                return ResourceManager.GetString("Error_Apr_Not_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Channel Name or Password is empty. 的當地語系化字串。
        /// </summary>
        public static string Error_Apr_String_Empty {
            get {
                return ResourceManager.GetString("Error_Apr_String_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Firmware Version: 的當地語系化字串。
        /// </summary>
        public static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Generate a QR Code 的當地語系化字串。
        /// </summary>
        public static string GenerateQrCode {
            get {
                return ResourceManager.GetString("GenerateQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The channel name and password have been saved. 的當地語系化字串。
        /// </summary>
        public static string Message_AprDataSaved {
            get {
                return ResourceManager.GetString("Message_AprDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Messsage 的當地語系化字串。
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Off 的當地語系化字串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 On 的當地語系化字串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Overview: 的當地語系化字串。
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password: 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string PasswordTitle {
            get {
                return ResourceManager.GetString("PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paste the saved data 的當地語系化字串。
        /// </summary>
        public static string PasteData {
            get {
                return ResourceManager.GetString("PasteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Port 的當地語系化字串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a port to connect. If no ports appear, please ensure the APR-1 is plugged in. 的當地語系化字串。
        /// </summary>
        public static string PortDescription {
            get {
                return ResourceManager.GetString("PortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return to homepage 的當地語系化字串。
        /// </summary>
        public static string ReturnToHomepage {
            get {
                return ResourceManager.GetString("ReturnToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save the data 的當地語系化字串。
        /// </summary>
        public static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transfer 的當地語系化字串。
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data updated. Closing transfer port. Please wait... 的當地語系化字串。
        /// </summary>
        public static string Transfer_Closing {
            get {
                return ResourceManager.GetString("Transfer_Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transfer completed. 的當地語系化字串。
        /// </summary>
        public static string Transfer_Completed {
            get {
                return ResourceManager.GetString("Transfer_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transfer started. 的當地語系化字串。
        /// </summary>
        public static string Transfer_Start {
            get {
                return ResourceManager.GetString("Transfer_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transmission Power Setting: 的當地語系化字串。
        /// </summary>
        public static string TransmissionPower {
            get {
                return ResourceManager.GetString("TransmissionPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transmission Quality: 的當地語系化字串。
        /// </summary>
        public static string TransmissionQuality {
            get {
                return ResourceManager.GetString("TransmissionQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transmission Quality 的當地語系化字串。
        /// </summary>
        public static string TransmissionQualityTitle {
            get {
                return ResourceManager.GetString("TransmissionQualityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TX Power 的當地語系化字串。
        /// </summary>
        public static string TXPower {
            get {
                return ResourceManager.GetString("TXPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update 的當地語系化字串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Volume 的當地語系化字串。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
