//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioRopa.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioRopa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 AGC (Automatic Gein Control): 的當地語系化字串。
        /// </summary>
        public static string AGC {
            get {
                return ResourceManager.GetString("AGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APR-1 的當地語系化字串。
        /// </summary>
        public static string APRDeviceText {
            get {
                return ResourceManager.GetString("APRDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APT-1 的當地語系化字串。
        /// </summary>
        public static string APTDeviceText {
            get {
                return ResourceManager.GetString("APTDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auracast Information 的當地語系化字串。
        /// </summary>
        public static string AuracastInformation {
            get {
                return ResourceManager.GetString("AuracastInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Channel Name: 的當地語系化字串。
        /// </summary>
        public static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose Your Device 的當地語系化字串。
        /// </summary>
        public static string ChooseYourDevice {
            get {
                return ResourceManager.GetString("ChooseYourDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connection: 的當地語系化字串。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connect to APT-1 的當地語系化字串。
        /// </summary>
        public static string ConnectToApt {
            get {
                return ResourceManager.GetString("ConnectToApt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device Name: 的當地語系化字串。
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Firmware Version: 的當地語系化字串。
        /// </summary>
        public static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Overview: 的當地語系化字串。
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password: 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transmission Power Setting: 的當地語系化字串。
        /// </summary>
        public static string TransmissionPower {
            get {
                return ResourceManager.GetString("TransmissionPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transmission Quality: 的當地語系化字串。
        /// </summary>
        public static string TransmissionQuality {
            get {
                return ResourceManager.GetString("TransmissionQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Volume 的當地語系化字串。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
