/* Copyright Statement:
 *
 * (C) 2020  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */
/* Airoha restricted information */

﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AudioRopa
{
    public enum MessageID
    {
		UNKNOWN = -1,

		NOTIFY_FROM_DEVICE,
		FW_VERSION,

		//DEVICE_LIST_INFO = 1001,
		DEVICE_NAME = 1001,
		SET_DEVICE_NAME = 1002,
		ANC_STATUS = 1003,
		MULTI_AI_STATUS = 1004,
		SET_MULTI_AI_STATUS = 1005,
		FIND_ME_STATUS = 1006,
		SET_FIND_ME_STATUS = 1007,
		//A2DP_STATUS = 1007,
		TWS_STATUS = 1009,
		SEALING_STATUS = 1010,
		DEVICE_INFO = 1012,
		BATTERY_STATUS = 1013,
		SMART_SWITCH_STATUS = 1016,
		SET_SMART_SWITCH_STATUS = 1017,
		DYNAMIC_LR_STATUS = 1019,
		TOUCH_STATUS = 1500,
		SET_TOUCH_STATUS = 1501,
		AUTO_PAUSE = 1502,
		SET_AUTO_PAUSE = 1503,
		AUTO_POWER_OFF = 1504,
		SET_AUTO_POWER_OFF = 1505,
		//SDK_INFO = 1501,
		//SHARE_MODE_STATE = 1502,
		SIDETONE_LEVEL = 1506,
		SET_SIDETONE_LEVEL = 1507,
		SIDETONE_STATE = 1508,
		SET_SIDETONE_STATE = 1509,
		VOICE_PROMPTS_STATUS = 1510,
		SET_VOICE_PROMPTS_STATUS = 1511,

		//FOTA_STATUS = 2001,

		PEQ_INFO = 3001,
		RUNNING_PEQ_STATUS = 3002,
		SET_EQ_INDEX = 3003,
		REALTIME_UPDATE_EQ = 3004,
		SAVE_EQ_STATUS = 3005,

		GESTURE_INFO = 4001,
		SET_GESTURE_STATUS = 4002,

		ANTENNA_INFO = 5001,
		MMI_STATE = 5002,
		HANDLE_PHONE_STATUS = 5003,
		SET_FACTORY_RESET = 5004,
		DONGLE_RSSI = 5005,

		GET_GAME_CHAT_BALANCE_SETTINGS = 6000,
		SET_GAME_CHAT_BALANCE_SETTINGS = 6001,
		GAME_CHAT_RATIO = 6002,
		GAME_MIC_VOLUME = 6003,

		ADVANCED_PASSTHROUGH_STATUS = 7000,
		SET_ADVANCED_PASSTHROUGH_STATUS = 7001,
		ENVIRONMENT_DETECTION_INFO = 7002,
		ENVIRONMENT_DETECTION_STATUS = 7003,
		SET_ENVIRONMENT_DETECTION_STATUS = 7004,

		AUDIO_FEATURE_CAPABILITY = 9000,
		CHIP_SETTING = 9001,
		DEVICE_TYPE = 9002,
		AGENT_CHANNEL = 9003,
		SEND_CUSTOM_CMD = 9999,

		PROGRESS = 10000,
		NORMAL,
		TASK_TIMEOUT_RETRY,
		QUERY_SINGLE_FOTA_INFO,
		QUERY_DUAL_FOTA_INFO,
		DEVICE_CANCEL,
		DFU_PING,
		RECONNECT,
		CONNECT,
		COMMIT,
		FOTA_STATUS,
		INTEGRITY_CHECK_SUCCESS,
		DFU_SUCCESS,
		DFU_FAIL,
		DFU_USER_CANCEL,
		BATTERY_LOW,
		READ_WRITE_ERROR,
		LOG_DUMP_PROGRESS,

		// LEA
		LEA_DONGLE_STREAM_MODE = 14000,
		SET_LEA_DONGLE_STREAM_MODE = 14001,
		LEA_SCAN_NOTIFICATION = 15000,
		LEA_GET_REMOTE_DEVICE_LIST,
		LEA_REMOTE_CONNECTED,
		LEA_REMOTE_DISCONNECTED,
		LEA_GET_REMOTE_DEVICE_STATUS,
		LEA_GET_AUDIO_ACTIVE_DEV,
		LEA_GET_AUDIO_BROADCAST_DEV,
		LEA_REMOVE_PAIRED_RECORD,
		LEA_GET_LINK_TYPE,
		LEA_GET_DONGLE_MODE,
		LEA_SET_DONGLE_MODE,
		LEA_DONGLE_BIS_NAME,
		LEA_DONGLE_BIS_QOS,
		LEA_DONGLE_BIS_CODE,

		// custom
		MCU_COMMIT = 20000,
		MCU_CHECK_INTEGRITY,
		MCU_STATE,
		MCU_UPDATE_SUCCESS,
		UNKNOWN_NOTIFY_FROM_DEVICE,

		CUSTOM_READ_NV,
		CUSTOM_WRITE_NV,
		CUSTOM_RACE,
		WEAR_DETECTION_MIC_ONOFF,
		BUSY_LIGHT_STATUS,
		UC_PROFILE,
		UC_APP_STATUS,
		NOTIFICATION_ACTIVATION,
		NOTIFICATION_MAP,
		TELEMETRY_DATA,
		LOOPBACK_DATA,
		VOICE_GUIDANCE,
		DIS_INFORMATION,
		BT_MULTI_HOST_NAME,

		// common
		SKIP_TIMEOUT = 30000,
	}
}
